import { GridpointForecastPeriod } from "../../types/weatherTypes";

export const TEST_FORECAST_DATA: GridpointForecastPeriod[] = [
  {
    number: 1,
    name: "Tonight",
    startTime: "2023-08-06T19:00:00-05:00",
    endTime: "2023-08-07T06:00:00-05:00",
    isDaytime: false,
    temperature: 60,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: null,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 17.777777777777779,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 93,
    },
    windSpeed: "10 to 15 mph",
    windDirection: "NW",
    icon: "https://api.weather.gov/icons/land/night/few?size=medium",
    shortForecast: "Mostly Clear",
    detailedForecast:
      "Mostly clear, with a low around 60. Northwest wind 10 to 15 mph, with gusts as high as 25 mph.",
  },
  {
    number: 2,
    name: "Monday",
    startTime: "2023-08-07T06:00:00-05:00",
    endTime: "2023-08-07T18:00:00-05:00",
    isDaytime: true,
    temperature: 82,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: null,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 17.222222222222221,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "5 to 10 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
    shortForecast: "Mostly Sunny",
    detailedForecast:
      "Mostly sunny, with a high near 82. North wind 5 to 10 mph.",
  },
  {
    number: 3,
    name: "Monday Night",
    startTime: "2023-08-07T18:00:00-05:00",
    endTime: "2023-08-08T06:00:00-05:00",
    isDaytime: false,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 17.222222222222221,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 90,
    },
    windSpeed: "5 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/bkn/tsra_hi,20?size=medium",
    shortForecast: "Mostly Cloudy then Slight Chance Showers And Thunderstorms",
    detailedForecast:
      "A slight chance of showers and thunderstorms after 1am. Mostly cloudy, with a low around 63. Northeast wind around 5 mph. Chance of precipitation is 20%.",
  },
  {
    number: 4,
    name: "Tuesday",
    startTime: "2023-08-08T06:00:00-05:00",
    endTime: "2023-08-08T18:00:00-05:00",
    isDaytime: true,
    temperature: 83,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 18.888888888888889,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 93,
    },
    windSpeed: "5 to 10 mph",
    windDirection: "SE",
    icon: "https://api.weather.gov/icons/land/day/tsra_hi,20?size=medium",
    shortForecast: "Slight Chance Showers And Thunderstorms",
    detailedForecast:
      "A slight chance of showers and thunderstorms. Mostly sunny, with a high near 83. Southeast wind 5 to 10 mph. Chance of precipitation is 20%.",
  },
  {
    number: 5,
    name: "Tuesday Night",
    startTime: "2023-08-08T18:00:00-05:00",
    endTime: "2023-08-09T06:00:00-05:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 70,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 19.444444444444443,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 97,
    },
    windSpeed: "10 mph",
    windDirection: "SE",
    icon: "https://api.weather.gov/icons/land/night/tsra_hi,40/tsra_hi,70?size=medium",
    shortForecast: "Chance Showers And Thunderstorms",
    detailedForecast:
      "A chance of showers and thunderstorms before 1am, then showers and thunderstorms likely. Mostly cloudy, with a low around 64. Southeast wind around 10 mph. Chance of precipitation is 70%.",
  },
  {
    number: 6,
    name: "Wednesday",
    startTime: "2023-08-09T06:00:00-05:00",
    endTime: "2023-08-09T18:00:00-05:00",
    isDaytime: true,
    temperature: 81,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 70,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20.555555555555557,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "10 to 15 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/tsra_hi,70/tsra_hi,50?size=medium",
    shortForecast:
      "Showers And Thunderstorms Likely then Chance Showers And Thunderstorms",
    detailedForecast:
      "Showers and thunderstorms likely before 7am, then a chance of showers and thunderstorms. Partly sunny, with a high near 81. Northeast wind 10 to 15 mph, with gusts as high as 20 mph. Chance of precipitation is 70%.",
  },
  {
    number: 7,
    name: "Wednesday Night",
    startTime: "2023-08-09T18:00:00-05:00",
    endTime: "2023-08-10T06:00:00-05:00",
    isDaytime: false,
    temperature: 62,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20.555555555555557,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "5 to 10 mph",
    windDirection: "E",
    icon: "https://api.weather.gov/icons/land/night/tsra_hi,20/few?size=medium",
    shortForecast: "Slight Chance Showers And Thunderstorms then Mostly Clear",
    detailedForecast:
      "A slight chance of showers and thunderstorms before 7pm. Mostly clear, with a low around 62. East wind 5 to 10 mph. Chance of precipitation is 20%.",
  },
  {
    number: 8,
    name: "Thursday",
    startTime: "2023-08-10T06:00:00-05:00",
    endTime: "2023-08-10T18:00:00-05:00",
    isDaytime: true,
    temperature: 87,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: null,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "5 to 10 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
    shortForecast: "Mostly Sunny",
    detailedForecast:
      "Mostly sunny, with a high near 87. South wind 5 to 10 mph.",
  },
  {
    number: 9,
    name: "Thursday Night",
    startTime: "2023-08-10T18:00:00-05:00",
    endTime: "2023-08-11T06:00:00-05:00",
    isDaytime: false,
    temperature: 66,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20.555555555555557,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 93,
    },
    windSpeed: "10 mph",
    windDirection: "SW",
    icon: "https://api.weather.gov/icons/land/night/few/tsra_hi,20?size=medium",
    shortForecast: "Mostly Clear then Slight Chance Showers And Thunderstorms",
    detailedForecast:
      "A slight chance of showers and thunderstorms after 1am. Mostly clear, with a low around 66. Southwest wind around 10 mph. Chance of precipitation is 20%.",
  },
  {
    number: 10,
    name: "Friday",
    startTime: "2023-08-11T06:00:00-05:00",
    endTime: "2023-08-11T18:00:00-05:00",
    isDaytime: true,
    temperature: 89,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20.555555555555557,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "10 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/tsra_hi,20/few?size=medium",
    shortForecast: "Slight Chance Showers And Thunderstorms then Sunny",
    detailedForecast:
      "A slight chance of showers and thunderstorms before 7am. Sunny, with a high near 89. Chance of precipitation is 20%.",
  },
  {
    number: 11,
    name: "Friday Night",
    startTime: "2023-08-11T18:00:00-05:00",
    endTime: "2023-08-12T06:00:00-05:00",
    isDaytime: false,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20.555555555555557,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 97,
    },
    windSpeed: "10 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/tsra_hi,20?size=medium",
    shortForecast: "Slight Chance Showers And Thunderstorms",
    detailedForecast:
      "A slight chance of showers and thunderstorms after 7pm. Mostly clear, with a low around 63. Chance of precipitation is 20%.",
  },
  {
    number: 12,
    name: "Saturday",
    startTime: "2023-08-12T06:00:00-05:00",
    endTime: "2023-08-12T18:00:00-05:00",
    isDaytime: true,
    temperature: 85,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 20,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 18.888888888888889,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 97,
    },
    windSpeed: "10 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/tsra_hi,20/sct?size=medium",
    shortForecast: "Slight Chance Showers And Thunderstorms then Mostly Sunny",
    detailedForecast:
      "A slight chance of showers and thunderstorms before 7am. Mostly sunny, with a high near 85. Chance of precipitation is 20%.",
  },
  {
    number: 13,
    name: "Saturday Night",
    startTime: "2023-08-12T18:00:00-05:00",
    endTime: "2023-08-13T06:00:00-05:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 30,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 19.444444444444443,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "10 mph",
    windDirection: "E",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20/tsra_hi,30?size=medium",
    shortForecast: "Chance Showers And Thunderstorms",
    detailedForecast:
      "A slight chance of rain showers between 7pm and 1am, then a chance of showers and thunderstorms. Partly cloudy, with a low around 64. Chance of precipitation is 30%.",
  },
  {
    number: 14,
    name: "Sunday",
    startTime: "2023-08-13T06:00:00-05:00",
    endTime: "2023-08-13T18:00:00-05:00",
    isDaytime: true,
    temperature: 84,
    temperatureUnit: "F",
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: 30,
    },
    dewpoint: {
      unitCode: "wmoUnit:degC",
      value: 20,
    },
    relativeHumidity: {
      unitCode: "wmoUnit:percent",
      value: 100,
    },
    windSpeed: "10 to 15 mph",
    windDirection: "SE",
    icon: "https://api.weather.gov/icons/land/day/tsra_hi,30?size=medium",
    shortForecast: "Chance Showers And Thunderstorms",
    detailedForecast:
      "A chance of showers and thunderstorms. Mostly sunny, with a high near 84. Chance of precipitation is 30%.",
  },
];
